import argparse
import json
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
os.environ.setdefault("YOLO_CONFIG_DIR", str(BASE_DIR / ".ultralytics"))

try:
    from ultralytics import YOLO
except Exception as exc:
    raise SystemExit(
        "Failed to import ultralytics. Run `pixi install` and make sure `torchvision` is available.\n"
        f"Original error: {exc}"
    ) from exc

ANNOTATIONS_PATH = BASE_DIR / "raw_data" / "NM_NGD_coco_dataset" / "train" / "annotations.json"
DATASET_DIR = BASE_DIR / "dataset"
GENERATED_DATASET_YAML = BASE_DIR / ".generated_dataset.yaml"


def parse_args():
    parser = argparse.ArgumentParser(description="Train a YOLOv8 baseline for NorgesGruppen object detection.")
    parser.add_argument("--model", default="yolov8m.pt", help="Pretrained YOLO checkpoint to start from.")
    parser.add_argument("--epochs", type=int, default=100, help="Number of training epochs.")
    parser.add_argument("--imgsz", type=int, default=1280, help="Training image size.")
    parser.add_argument("--batch", type=int, default=4, help="Batch size.")
    parser.add_argument("--device", default=None, help="Device override, for example '0' or 'cpu'.")
    parser.add_argument("--workers", type=int, default=4, help="Number of dataloader workers.")
    parser.add_argument("--project", default=str(BASE_DIR / "runs" / "detect"), help="Output project directory.")
    parser.add_argument("--name", default="ngd_yolov8m", help="Run name inside the project directory.")
    parser.add_argument("--cache", action="store_true", help="Enable Ultralytics image caching.")
    parser.add_argument("--exist-ok", action="store_true", help="Reuse an existing run directory.")
    return parser.parse_args()


def load_category_names(annotations_path: Path) -> list[str]:
    with annotations_path.open(encoding="utf-8") as handle:
        data = json.load(handle)

    categories = sorted(data["categories"], key=lambda item: item["id"])
    category_ids = [item["id"] for item in categories]
    expected_ids = list(range(len(categories)))

    if category_ids != expected_ids:
        raise ValueError("Category IDs are not contiguous from 0..N-1, which YOLO training expects.")

    return [item["name"] or f"class_{item['id']}" for item in categories]


def write_runtime_dataset_yaml(output_path: Path, dataset_dir: Path, names: list[str]) -> Path:
    lines = [
        "# Auto-generated by train.py",
        f"path: {json.dumps(dataset_dir.resolve().as_posix(), ensure_ascii=False)}",
        "train: images/train",
        "val: images/val",
        "test: images/val",
        f"nc: {len(names)}",
        "names:",
    ]

    for class_id, name in enumerate(names):
        lines.append(f"  {class_id}: {json.dumps(name, ensure_ascii=False)}")

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_path


def validate_dataset(dataset_dir: Path) -> None:
    required_dirs = [
        dataset_dir / "images" / "train",
        dataset_dir / "images" / "val",
        dataset_dir / "labels" / "train",
        dataset_dir / "labels" / "val",
    ]

    missing = [str(path) for path in required_dirs if not path.exists()]
    if missing:
        raise FileNotFoundError(
            "Dataset folders are missing. Run convert.py first.\nMissing paths:\n" + "\n".join(missing)
        )


def main():
    args = parse_args()
    validate_dataset(DATASET_DIR)

    class_names = load_category_names(ANNOTATIONS_PATH)
    runtime_yaml = write_runtime_dataset_yaml(GENERATED_DATASET_YAML, DATASET_DIR, class_names)

    model = YOLO(args.model)
    train_kwargs = {
        "data": str(runtime_yaml),
        "epochs": args.epochs,
        "imgsz": args.imgsz,
        "batch": args.batch,
        "workers": args.workers,
        "project": args.project,
        "name": args.name,
        "exist_ok": args.exist_ok,
        "cache": args.cache,
        "seed": 42,
    }

    if args.device:
        train_kwargs["device"] = args.device

    model.train(**train_kwargs)

    print(f"Training complete. Runtime dataset config: {runtime_yaml}")
    print(f"Run directory: {Path(args.project) / args.name}")


if __name__ == "__main__":
    main()
